### ISSUE TITLE
Trust from front to back end

### ISSUE THREAD

**Issue by danmermel** [glynnbird/choirless#11]
- how do you pass trust from the front end to the back end (the sense of who the caller is who is making the call)

**Comment by glynnbird** [comment]
According to [the docs](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-context.html) the context parameter (the second parameter passed to a JavaScript Lambda is an object which contains `identity. cognitoIdentityId` which should be the identity of the authorised user.

We could use this as a sanity check in:

- `postChoir` to make sure that the passed-in `createdByUserId` matches the value in the context.
- `postChoirJoin` to make sure that the passed-in `userId` matches the value in the context.
- `postChoirSong` to make sure that the passed-in `userId` matches the value in the context.
- `postChoirSongPart` to make sure that the passed-in `userId` matches the value in the context.

Additional security (optional):

- in `postTokenGenerate` make sure that the user in the context is the leader of the choir they are generating the token for.
- in `postChoirSongPartUpload` make sure that the user in the context is a member of the choir and the originator of the song part being uploaded.
- etc

**Comment by danmermel** [comment]
identity. cognitoIdentityId is the federated id and NOT the user pool id and Tim could not find a way of getting from one to the other..

So basically it looks like if we want to tighten up here we are going to have to reinstate the API gateway... stand by for more details!
