### ISSUE TITLE
add workspace to cognito pool resources

### ISSUE THREAD

**Issue by danmermel** [glynnbird/choirless#44]
we are not adding the stage/prod workspace name to the cognito pool (and maybe other) resources when creating them in terraform. So it will all break when we deploy to production...

So let's make sure that is corrected

**Comment by glynnbird** [comment]
To check this I altered `cognito.tf` and did `terraform plan` to see what it would do:

-  name                = "choirless_cognito_pool"
+  name                = "choirless_cognito_pool_${terraform.workspace}"

and it would destroy and recreate the entire Cognito infrastructure.

So easy change, but total destruction of users and the data in the database would be orphaned.
