### ISSUE TITLE
T&C frigs

### ISSUE THREAD

**Issue by danmermel** [glynnbird/choirless#79]
* Who wants a name check?
* This data is stored in data centres in the United Kingdom -- we need to either do that or change this
* Need a gdpr@choirless.com alias because the T&C says: Choirless is the responsible party in terms of GDPR and we may be contacted with an email to gdpr@choirless.com.
* Need dmca@choirless.com alias (takedown requests under the Digital Millennium Copyright Act (DMCA) should be directed to dmca@choirless.com)
* There is Marketing heading with no content.. the content on the current site says: Marketing - By using Choirless you agree to us using materials generated with Choirless technologies for those purposes in perpetuity without compensation.
* * This makes no sense.. what purposes?

**Comment by glynnbird** [comment]
> There is Marketing heading with no content.. the content on the current site says: Marketing - By using Choirless you agree to us using materials generated with Choirless technologies for those purposes in perpetuity without compensation.

On old Choirless, we wanted to retain the right to use finished videos for other purposes e.g. PR.
